apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations:
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
data:
  config.yaml: |
  {{- with .Values.config -}}
    {{- toYaml . | nindent 4 }}
  {{- end }}